### ISSUE TITLE
Bootstrap 4 ... where?

### ISSUE THREAD

**Issue by TEnders64** [jfrazx/detector#1]
Where exactly are the templates I can style up? Been out of this Angular game way too long! @jfrazx

**Comment by jfrazx** [comment]
You'll be spending most of your time in /src/app/**/* with *.html and *.css. ng-bootstrap is already installed and the required css linked in index.html. I have been focusing on file fingerprinting and similarity comparison ratings lately. I have one wireframe up currently and plan to work on more in the coming days, so there isn't much styling to do yet. 

You can familiarize yourself with the ins and out of ng-bootstrap if you are so inclined.
https://ng-bootstrap.github.io/#/home

**Comment by wesharper** [comment]
Why use ng-bootstrap rather than just plain bootstrap?

**Comment by jfrazx** [comment]
@wesharper  Bootstrap relies on non-Angular JavaScript, whereas ng-bootstrap has no external JS dependencies.

**Comment by jfrazx** [comment]
@TEnders64  
Switched to using Sass. 

Should be enough available to keep someone busy.
